# Generated by Django 6.0 on 2025-12-29 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ngành')),
            ],
            options={
                'verbose_name_plural': '1. Quản lý ngành',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vị trí/Khoang hầm')),
            ],
            options={
                'verbose_name_plural': '2. Danh mục vị trí',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Thuộc ngành')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('total_system_hours', models.FloatField(default=0.0, verbose_name='Tổng giờ tích luỹ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlthietbi.department', verbose_name='Thuộc ngành')),
            ],
            options={
                'verbose_name': '3. Hệ thống thiết bị (Cha)',
                'verbose_name_plural': '3. Hệ thống thiết bị (Cha)',
            },
        ),
        migrations.CreateModel(
            name='DeviceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khối')),
                ('qr_code', models.CharField(max_length=50, unique=True, verbose_name='Mã QR')),
                ('current_hours', models.FloatField(default=0.0, verbose_name='Giờ chạy')),
                ('maintenance_threshold', models.FloatField(default=500.0, verbose_name='Định mức bảo dưỡng')),
                ('status', models.CharField(choices=[('NORMAL', 'Hoạt động bình thường'), ('MAINTENANCE', 'Bảo dưỡng'), ('ERROR', 'Lỗi')], default='NORMAL', max_length=20, verbose_name='Trạng thái')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='qlthietbi.device', verbose_name='Thuộc Hệ thống')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qlthietbi.location', verbose_name='Vị trí lắp đặt')),
            ],
            options={
                'verbose_name': '4. Khối chi tiết',
                'verbose_name_plural': '4. Khối chi tiết',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=50, verbose_name='Người thực hiện')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bật')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian tắt')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Giờ hoạt động (h)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlthietbi.device', verbose_name='Chọn thiết bị')),
            ],
            options={
                'verbose_name': '5. Nhật ký máy',
                'verbose_name_plural': '5. Nhật ký máy',
            },
        ),
    ]
