# Generated by Django 6.0 on 2025-12-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlthietbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/devices/', verbose_name='Mã QR'),
        ),
        migrations.AddField(
            model_name='deviceunit',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/units/', verbose_name='Mã QR'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên thiết bị'),
        ),
    ]
