# Generated by Django 6.0 on 2025-12-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlthietbi', '0002_device_qr_image_deviceunit_qr_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='qr_image',
        ),
    ]
