# Generated by Django 5.2.4 on 2026-01-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlthietbi', '0003_remove_device_qr_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-start_time'], 'verbose_name': '5. Nhật ký máy', 'verbose_name_plural': '5. Nhật ký máy'},
        ),
        migrations.AddField(
            model_name='operationlog',
            name='device_status',
            field=models.CharField(choices=[('NORMAL', 'Hoạt động bình thường (C1)'), ('MAINTENANCE', 'Cần bảo dưỡng (C2)'), ('ERROR', 'Hỏng hóc/Sự cố')], default='NORMAL', max_length=20, verbose_name='Trạng thái thiết bị khi tắt máy'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='device_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qlthietbi.deviceunit', verbose_name='Khối chi tiết'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú/Mô tả vấn đề'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
