# Generated by Django 6.0 on 2026-01-29 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlthietbi', '0004_alter_operationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_verified', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operator_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Người thực hiện (Legacy)'),
        ),
    ]
