# Generated by Django 5.2.4 on 2026-01-29 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlthietbi', '0005_operationlog_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('description', models.TextField(verbose_name='Mô tả sự cố')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('HIGH', 'Cao'), ('CRITICAL', 'Khẩn cấp')], default='LOW', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('COMPLETED', 'Đã hoàn thành'), ('VERIFIED', 'Đã nghiệm thu'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('assigned_to_name', models.CharField(blank=True, max_length=100, verbose_name='Giao cho (Tên)')),
                ('solution', models.TextField(blank=True, verbose_name='Giải pháp sửa chữa')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Giao cho (User)')),
                ('device_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='qlthietbi.deviceunit', verbose_name='Khối thiết bị')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
            ],
            options={
                'verbose_name': '6. Lệnh bảo dưỡng/Sửa chữa',
                'verbose_name_plural': '6. Lệnh bảo dưỡng/Sửa chữa',
                'ordering': ['-created_at'],
            },
        ),
    ]
